### ISSUE TITLE
Game Device Control Panel

### ISSUE THREAD

**Issue by wanderschikanentv** [WallyCZ/saitek-cyborg-ff#1]
Hi,
I just dusted-off my Cyborg Evo Force and tried using it for the 1st time ever on DCS. After some crashes and a bit of Google research, I found this page and installed your Powershell script. But still, the joystick crashes DCS as well as the Game Device Control panel (when trying to test force feedback. I'm on Windows 11 64-bit.

What I had done:
1.) Plugged the Cyborg Evo Force into USB
2.) Had installed drivers according to this post: https://forum.il2sturmovik.com/topic/22605-how-to-install-saitek-cyborg-evo-force-64-bit-ffb-drivers/ 
updating both USB and HID device manually according to the dead link in the post (you can still access it via wayback machine)
3.) Started Powershell as Admin and run your script.

> Windows PowerShell
> Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.
> 
> Installieren Sie die neueste PowerShell für neue Funktionen und Verbesserungen! https://aka.ms/PSWindows
> 
> Warnung: PowerShell hat erkannt, dass Sie möglicherweise eine Sprachausgabe verwenden und PSReadline aus Kompatibilitätszwecken deaktiviert haben. Wenn Sie es erneut aktivieren möchten, führen Sie „Import-Modul psReadline” aus.
> 
> PS C:\WINDOWS\system32> d:
> PS D:\> \install.ps1
> 
> Sicherheitswarnung
> Führen Sie ausschließlich vertrauenswürdige Skripts aus. Skripts aus dem Internet können zwar nützlich sein, stellen
> jedoch auch eine potenzielle Gefahr für Ihren Computer dar. Wenn Sie diesem Skript vertrauen, lassen Sie mit dem Cmdlet
>  "Unblock-File" die Ausführung des Skripts ohne die Warnmeldung zu. Möchten Sie "D:\install.ps1" ausführen?
> [N] Nicht ausführen  [M] Einmal ausführen  [H] Anhalten  [?] Hilfe (Standard ist "N"): M
> Saitek Force Feedback driver fix (https://github.com/WallyCZ/saitek-cyborg-ff)
> Replacing Saitek Cyborg Evo Force driver
> Do you want to change device name (needed for same games like DCS) [Y/n]: Y
> 
> 
> OEMName      : Saitek Cyborg Evo FF
> PSPath       : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\P
>                rivateProperties\Joystick\OEM\VID_06A3&PID_FFB5
> PSParentPath : Microsoft.PowerShell.Core\Registry::HKEY_CURRENT_USER\System\CurrentControlSet\Control\MediaProperties\P
>                rivateProperties\Joystick\OEM
> PSChildName  : VID_06A3&PID_FFB5
> PSDrive      : HKCU
> PSProvider   : Microsoft.PowerShell.Core\Registry
> 
> 
> 
> PS D:\>

Any advice  what I may have done wrong, or I can fix it?

**Comment by WallyCZ** [comment]
I did not tested it on Win11 yet as well as on another machine, but I am pretty sure we make it working. 
According output of the script you were doing everything correctly and even the install script succeeded. So we need to check couple of things why it's still crashing.
1) Check your driver version in joystick control panel. It has to be 6.0.4.1 (latest). Install script is not checking it yet, so it could be a problem.
![image](https://user-images.githubusercontent.com/13380548/158482238-4250bba6-9a69-4ea0-8bf0-d6aee6caee90.png)
You can also try to reinstall them from [here](ftp://ftp.saitek.com/pub/software/full/Saitek_Cyborg_Evo_Force_SD6_64.exe) and then apply patch again.
2) If DCS crashed, you should be able to find crash report in zip file in path like this `c:\Users\<username>\Saved Games\DCS\Logs\dcs.log-<crash_datetime>.zip`. Please provide it, it contains valuable info.
3) With the powershell running as Administrator run these commands and give me the ouput:
 `[System.Diagnostics.FileVersionInfo]::GetVersionInfo([System.Environment]::SystemDirectory + "\SaiQFFB5.dll")`
 `dir ([System.Environment]::SystemDirectory + "\Sai*")`

**Comment by wanderschikanentv** [comment]
Hi Wally,
It worked in the meantime! I had uninstalled the joystick, removed temp folders from C: drive and Saitek registry entries. After restart, the joystick reappeared with Saitek drivers, and I re-ran your script with the change-name option. Now it works :-)

Honestly, I couldn't re-do the procedure without trial and error, but your script is really awesome. I definitely appreciate your effort, keeping this piece of hardware alive.

THX!

**Comment by WallyCZ** [comment]
Glad it is now working! Yeah, there is not many joysticks with force feedback on the market now, so we must keep them alive.
